import {JetBrains_Mono} from "next/font/google";
import "./globals.css";


//components
import Header from "@/components/Header";
import Page_Transition from "@/components/Page_Transition";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable:"--font-jetbrainsMono",

})

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={jetbrainsMono.variable}
      >
        <Header />
        <Page_Transition>  {children}</Page_Transition>
      
      </body>
    </html>
  );
}
